testingisdocumenting/webtau

webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy

Fixes https://github.com/twosigma/webtau/issues/18

Return non-0 code if tests fail or error

---

webtau-core/src/main/java/com/twosigma/webtau/expectation/ActualValue.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/ExpectationHandlers.java
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/ActualValueTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/contain/ContainMatcherTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/contain/handlers/IterableContainHandlerTest.groovy
webtau-junit5/src/main/java/com/twosigma/webtau/junit5/report/JavaBasedTest.java
webtau-report/src/main/java/com/twosigma/webtau/report/ReportTestEntry.java
webtau-rest/src/main/java/com/twosigma/webtau/http/Http.java
webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTest.groovy
webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestTest.groovy

Looks like I picked previous commit again somehow. Time to read git book again. I will not mess this time with rebased.

call custom expectation handlers for shouldNot

---

webtau-rest-groovy/src/test/groovy/com/twosigma/webtau/http/HttpTest.groovy
webtau-rest/src/main/java/com/twosigma/webtau/http/datanode/StructuredDataNode.java

fix `find`, `findAll`, `collect` for `body` that is not a list

---

webtau-reactjs/src/report/OverallSummary.css
webtau-reactjs/src/report/OverallSummary.js
webtau-reactjs/src/report/Report.js
webtau-reactjs/src/report/WebTauReport.js
webtau-reactjs/src/report/WebTauReportStateCreator.js
webtau-reactjs/src/report/details/http/HttpCallDetails.css
webtau-reactjs/src/report/details/http/HttpCallDetails.js
webtau-reactjs/src/report/navigation/ListOfHttpCalls.js
webtau-reactjs/src/report/navigation/StatusFilter.js

add url coverage information to html report

---

.gitignore
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiSpecValidator.java

Fixes https://github.com/twosigma/webtau/issues/59

Enable validation of requests vs open api spec

---

webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiCoverageRecorder.java
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiResponseValidator.java
webtau-open-api/src/main/resources/META-INF/services/com.twosigma.webtau.http.validation.HttpValidationHandler
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiResponseValidatorTest.groovy

Documentation will be added once end to end feature testing is implemented (#85)

add a way to locally disable swagger validation

---

webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java

Additionally we fail now on any first should assertion instead of exercising all of them at once

validate and report statusCode problem in case of other assertions

---

webtau-docs/webtau/REST/openAPI-spec.md
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApi.java
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiSpecConfig.java
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiSpecValidator.java
webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiValidationConfig.java
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiSpecValidatorTest.groovy

add initial swagger config 'ignore additional properties'. Closing #25 and when we need more, we have a place to add more.

Swagger config

---

webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java
webtau-console/src/main/java/com/twosigma/webtau/console/ansi/NoAnsiConsoleOutput.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/ConsoleStepReporter.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/TokenizedMessage.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/TokenizedMessageToAnsiConverter.java
webtau-core/src/test/groovy/com/twosigma/webtau/reporter/ConsoleStepReporterTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/reporter/TokenizedMessageToAnsiConverterTest.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyFileConfigHandler.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy

Can't rely on System.console() == null since it is the case when running
from IDE. There is no easy way to check in java if output is being
redirected. So instead relying on a explicit flag

add ansi color config to toggle

---

webtau-http-groovy/src/main/groovy/com/twosigma/webtau/http/datanode/GroovyDataNode.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/DataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/NullDataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/StructuredDataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/validation/HeaderDataNode.java
webtau-http/src/test/groovy/com/twosigma/webtau/http/datanode/StructuredDataNodeTest.groovy

return null-node when list projection doesn't contain requested property

---

webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauTestRunner.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy

move triggerConfigHandlers out of cli to feature test runner

---

.gitignore
webtau-docs/webtau/REST/test-execution.md
webtau-docs/webtau/configuration/options.md
webtau-docs/webtau/toc
webtau-groovy/src/test/groovy/com/twosigma/webtau/cfg/CLIArgsTest.groovy

Adding documentation for parallel test execution and for configuration options.  I struggled a bit with where to put both bits of documentation to be honest so if you have any better ideas I'm all ears.
Preview:

Documentation updates

---

webtau-reactjs/src/report/details/http/ElapsedTime.js
webtau-reactjs/src/report/details/http/TestHttpCalls.css
webtau-reactjs/src/report/details/http/TestHttpCalls.js
webtau-reactjs/src/test-data/testData.js

when expanded, show full url on http calls tab

---

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/data/render/TableDataRenderTest.groovy
webtau-core/src/main/java/com/twosigma/webtau/Ddjt.java
webtau-core/src/test/groovy/com/twosigma/webtau/data/table/TableDataTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/IterableAndTableDataCompareToHandlerTest.groovy
webtau-core/src/test/java/com/twosigma/webtau/documentation/MarginCalculatorWithTableDataTest.java
webtau-core/src/test/java/com/twosigma/webtau/documentation/PeopleDaoTest.java
webtau-core/src/test/java/com/twosigma/webtau/documentation/PeopleManagementTest.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java

rename header builder method to table

---

.gitignore
.travis.yml
webtau-feature-testing/pom.xml
webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauTestRunner.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauRestFeaturesTest.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
webtau-junit4-examples/pom.xml
webtau-junit4-examples/src/test/java/com/example/tests/junit4/CustomerCrudSingleJavaTest.java
webtau-pdf/src/test/groovy/com/twosigma/webtau/pdf/PdfHttpTest.groovy
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServer.java
webtau-testapp/src/main/java/com/example/demo/springboot/app/SpringBootDemoApp.java
webtau-utils/src/main/java/com/twosigma/webtau/utils/UrlUtils.java
webtau-utils/src/test/groovy/com/twosigma/webtau/utils/UrlUtilsTest.groovy

Run test servers on random free ports

---

pom.xml
webtau-reactjs/package-lock.json
webtau-reactjs/package.json
webtau-reactjs/src/index.js
webtau-reactjs/src/report/ReportComponentsViewer.js
webtau-reactjs/src/report/WebTauReports.demo.js
webtau-reactjs/src/report/compression/reportDataCompression.js
webtau-reactjs/src/report/compression/reportDataCompression.test.js
webtau-reactjs/src/report/loading/Loading.css
webtau-reactjs/src/report/loading/Loading.demo.js
webtau-reactjs/src/report/loading/Loading.js
webtau-report/pom.xml
webtau-report/src/main/java/com/twosigma/webtau/report/HtmlReportGenerator.java
webtau-report/src/main/java/com/twosigma/webtau/report/ReportDataCompressor.java
webtau-report/src/test/groovy/com/twosigma/webtau/report/HtmlReportGeneratorTest.groovy
webtau-report/src/test/groovy/com/twosigma/webtau/report/ReportDataCompressorTest.groovy

compress report data and un-compress at client side

---

webtau-docs/webtau/REST/data-node.md
webtau-http-groovy/src/main/groovy/com/twosigma/webtau/http/datanode/GroovyDataNode.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/DataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/NullDataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/StructuredDataNode.java
webtau-http/src/main/java/com/twosigma/webtau/http/validation/HeaderDataNode.java

add DataNode.each with shortcut for list of complex values

---

webtau-config/src/main/java/com/twosigma/webtau/cfg/ConfigValue.java
webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java
webtau-feature-testing/examples/scenarios/rest/redirect/redirectOff.groovy
webtau-feature-testing/examples/scenarios/rest/redirect/redirectOn.groovy
webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauTestRunner.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauRestFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/rest/redirect/redirectOff/run-details.json
webtau-feature-testing/test-expectations/scenarios/rest/redirect/redirectOn/run-details.json
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServerRedirectResponse.java
webtau-utils/src/main/java/com/twosigma/webtau/utils/StringUtils.java
webtau-utils/src/test/groovy/com/twosigma/webtau/utils/StringUtilsTest.groovy

closes https://github.com/twosigma/webtau/issues/268

make following redirects optional

---

webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java
webtau-feature-testing/test-expectations/scenarios/rest/redirect/redirectOn/run-details.json
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
webtau-http/src/main/java/com/twosigma/webtau/http/HttpHeader.java
webtau-http/src/main/java/com/twosigma/webtau/http/HttpResponse.java
webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpHeaderTest.groovy
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java

Closes https://github.com/twosigma/webtau/issues/269.
I chose 20 as the default as that is what `HttpURLConnection` uses.

Follow redirects instead of relying on HttpURLConnection

---

webtau-http/src/main/java/com/twosigma/webtau/http/HttpHeader.java
webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationResult.java
webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpHeaderTest.groovy

rename HttpHeader.toMap to toListOfMaps

---

webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/handlers/ArrayAndIterableCompareToHandler.java
webtau-core/src/main/resources/META-INF/services/com.twosigma.webtau.expectation.equality.CompareToHandler
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/ArrayAndIterableCompareToHandlerTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/HandlerMessagesTest.groovy

Fixes https://github.com/twosigma/webtau/issues/151

Array compare to handler

---

webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/IgnoreAllConfigScriptClass.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyFileConfigHandler.groovy
webtau-groovy/src/test/groovy/com/twosigma/webtau/cfg/WebTauGroovyFileConfigHandlerTest.groovy
webtau-groovy/src/test/resources/webtau-nested.cfg

fix groovy config parsing to enable nested values

---

pom.xml
webtau-junit5-examples/pom.xml
webtau-junit5-examples/src/main/java/com/example/tests/junit5/PriceCalculator.java
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/DynamicTestsGroovyTest.groovy
webtau-junit5-groovy/pom.xml
webtau-junit5-groovy/src/main/groovy/com/twosigma/webtau/junit5/DynamicTestsExtensions.groovy
webtau-junit5-groovy/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule
webtau-junit5/src/main/java/com/twosigma/webtau/junit5/DynamicTests.java
webtau-junit5/src/test/java/com/twosigma/webtau/junit5/DynamicTestsTest.groovy

```
class DynamicTestsGroovyTest {
@TestFactory
def priceCalculator() {
["price", "quantity", "outcome"] {
_________________________________
10     |  30      |  300
-10    |  30      | -300
}.useCases {
PriceCalculator.calculate(price, quantity).should == outcome
}
}
}
```

junit5 dynamic tests from TableData

---

webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/GreaterLessEqualMatcherRenderer.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/GreaterThanMatcher.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/GreaterThanOrEqualMatcher.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/LessThanMatcher.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/LessThanOrEqualMatcher.java
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/GreaterThanMatcherTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/GreaterThanOrEqualMatcherTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/LessThanMatcherTest.groovy
webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/LessThanOrEqualMatcherTest.groovy

fix greater/less matchers toString impl

---

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/data/table/TableDataExtensionTest.groovy
webtau-core-groovy/src/test/groovy/com/twosigma/webtau/documentation/TestToDocExample.groovy
webtau-core/src/main/java/com/twosigma/webtau/Ddjt.java
webtau-core/src/main/java/com/twosigma/webtau/data/MultiValue.java
webtau-core/src/main/java/com/twosigma/webtau/data/table/Record.java
webtau-core/src/main/java/com/twosigma/webtau/data/table/TableData.java
webtau-core/src/main/java/com/twosigma/webtau/documentation/DocumentationArtifacts.java
webtau-core/src/main/java/com/twosigma/webtau/documentation/DocumentationArtifactsLocation.java
webtau-core/src/test/groovy/com/twosigma/webtau/data/table/TableDataTest.groovy
webtau-docs/webtau/lookup-paths
webtau-docs/webtau/reference/table-data.md
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/HttpDocumentation.java

```
["Col A"              | "Col B"         | "Col C"] {
___________________________________________________________
permute(true, false) | "v1b"           | permute('a', 'b')
"v2a"                | permute(10, 20) | "v2c" }
```

add table data permutation for input prep

---

webtau-docs/webtau/generic-runners/JUnit-5.md
webtau-docs/webtau/groovy-specific-runner/data-driven-scenarios.md

it is not groovy-runner specific as @MykolaGolubyev pointed out

move TestFactory doc to junit 5 runner 

---

webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunner.groovy
webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
webtau-standalone-runner-groovy/test-scripts/withExceptionOutside.groovy
webtau-standalone-runner-groovy/test-scripts/withParsingError.groovy

capture file parse failures as "init" failed test

---

webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/ForbidStepsOutsideScenarioStepListener.groovy
webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunner.groovy
webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
webtau-standalone-runner-groovy/test-scripts/withTestStepOutsideScenario.groovy

forbid executing any test steps outside of scenario

---

.travis.yml
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauFeaturesManualTestServer.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauUiFeaturesTest.groovy

Run end-to-end UI tests during build

---

.travis.yml
webtau-cache/src/test/groovy/com/twosigma/webtau/cache/FileBasedCacheTest.groovy
webtau-core/src/main/java/com/twosigma/webtau/documentation/DocumentationArtifacts.java
webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/ConfigFileEnvironmentsCollector.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyFileConfigHandler.groovy
webtau-groovy/src/test/groovy/com/twosigma/webtau/cfg/WebTauGroovyCliArgsConfigHandlerTest.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-pdf/src/main/java/com/twosigma/webtau/pdf/PdfText.java
webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestTest.groovy
webtau-utils/src/test/groovy/com/twosigma/webtau/utils/JsonUtilsTest.groovy
webtau-utils/src/test/groovy/com/twosigma/webtau/utils/ResourceUtilsTest.groovy

make windows build work

---

webtau-browser/src/main/java/com/twosigma/webtau/browser/driver/CurrentWebDriver.java
webtau-browser/src/main/java/com/twosigma/webtau/browser/driver/WebDriverCreator.java
webtau-browser/src/main/java/com/twosigma/webtau/browser/driver/WebDriverCreatorListener.java
webtau-browser/src/main/java/com/twosigma/webtau/browser/driver/WebDriverCreatorListeners.java
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy

clear driver thread local reference on driver quit

---

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/data/table/TableDataGroovyTest.groovy
webtau-core/src/main/java/com/twosigma/webtau/data/math/DynamicMath.java
webtau-core/src/main/java/com/twosigma/webtau/data/math/NumbersSimpleMathHandler.java
webtau-core/src/main/java/com/twosigma/webtau/data/math/SimpleMathHandler.java
webtau-core/src/main/java/com/twosigma/webtau/data/table/TableData.java
webtau-core/src/main/java/com/twosigma/webtau/data/table/autogen/TableDataCellValueGenerator.java
webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/CompareToComparator.java
webtau-core/src/main/resources/META-INF/services/com.twosigma.webtau.data.math.SimpleMathHandler
webtau-core/src/test/groovy/com/twosigma/webtau/data/math/DynamicMathTest.groovy
webtau-core/src/test/java/com/twosigma/webtau/data/table/TableDataJavaTest.java
webtau-core/src/test/java/com/twosigma/webtau/data/table/TableDataJavaTestValidations.java
webtau-docs/webtau/reference/table-data.md

add dynamic math. add table data cell.above plus/minus doc

---

webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyCliArgsConfigHandler.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy
webtau-groovy/src/test/groovy/com/twosigma/webtau/cfg/WebTauGroovyCliArgsConfigHandlerTest.groovy

Recursive scenario file discovery

---

webtau-http/src/main/java/com/twosigma/webtau/http/HttpHeader.java
webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpHeaderTest.groovy

Support merging HttpHeader with HttpHeader

---

webtau-cli/pom.xml
webtau-cli/scripts/hello
webtau-cli/src/main/java/com/twosigma/webtau/cli/Cli.java
webtau-cli/src/main/java/com/twosigma/webtau/cli/ProcessUtils.java
webtau-cli/src/main/java/com/twosigma/webtau/cli/parser/CommandParser.java
webtau-cli/src/test/groovy/com/twosigma/webtau/cli/ProcessUtilsTest.groovy
webtau-cli/src/test/java/com/twosigma/webtau/cli/CliJavaTest.java

cli run respect quotes

---

.gitignore
webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauEndToEndTestRunner.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauRestFeaturesTest.groovy
webtau-report-testing/src/test/groovy/pages/ReportLocation.groovy
webtau-report-testing/src/test/groovy/scenarios/crudOverview.groovy
webtau-report-testing/src/test/groovy/scenarios/crudSeparatedOverview.groovy

stop webtau feature tests from overriding html reports

---

webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/HttpDocumentation.java
webtau-http/src/main/java/com/twosigma/webtau/http/validation/HeaderDataNode.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/ResponseUtils.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServerRequestHeaderAndBodyEcho.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServerRequestHeaderEcho.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServerResponseEcho.java
webtau-utils/src/main/java/com/twosigma/webtau/utils/JsonUtils.java
webtau-utils/src/test/groovy/com/twosigma/webtau/utils/JsonUtilsTest.groovy

Closes https://github.com/twosigma/webtau/issues/354.

Capture response headers and redact all captured headers

---

webtau-docs/webtau/REST/documentation.md
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
webtau-http/src/main/java/com/twosigma/webtau/http/HttpDocumentation.java
webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationResult.java
webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpValidationResultTest.groovy
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiCoverageTest.groovy
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-open-api/src/test/groovy/com/twosigma/webtau/openapi/OpenApiSpecValidatorTest.groovy

Capture HTTP URLs for documentation

---

webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/DataNodeBuilder.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java

Handle primitive json responses

---

webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/HttpDocumentation.java

capture http method and operation for docs

---

webtau-http/pom.xml

Move slf4j-simple dependency to test

---

webtau-reactjs/src/report/summary/overal-info/HttpCallsTiming.js
webtau-reactjs/src/report/widgets/CardWithElapsedTime.demo.js
webtau-reactjs/src/report/widgets/CardWithElapsedTime.js

fix report time in ms weird decimals

---

pom.xml
webtau-cache/pom.xml
webtau-cli-groovy/pom.xml
webtau-cli/pom.xml
webtau-config/pom.xml
webtau-console/pom.xml
webtau-core-groovy/pom.xml
webtau-core/pom.xml
webtau-dist/pom.xml
webtau-feature-testing/pom.xml
webtau-groovy-ast/pom.xml
webtau-groovy/pom.xml
webtau-http-groovy/pom.xml
webtau-json-schema/pom.xml
webtau-junit5-groovy/pom.xml
webtau-maven-plugin-test-skip/pom.xml
webtau-maven-plugin-test/pom.xml
webtau-maven-plugin/pom.xml
webtau-open-api/pom.xml
webtau-pdf/pom.xml
webtau-report/pom.xml
webtau-shaded/pom.xml
webtau-standalone-runner-groovy/pom.xml
webtau-test-server/pom.xml
webtau-utils/pom.xml

reduce groovy deps footprint

---

webtau-docs/webtau/REST/data-node.md
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/test/java/com/twosigma/webtau/http/HttpJavaTest.java

Document node access by path

---

webtau-core/src/main/java/com/twosigma/webtau/data/traceable/TraceableValue.java
webtau-docs/webtau/REST/data-node.md
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/GroovyDataNodeTest.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/datanode/DataNode.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
webtau-http/src/test/resources/addressResponse.json

Addresses #227 for the most part.
The complex types are still not properly handled due to Groovy impl details.

DataNode if-else comparison capabilities

---

webtau-shaded/pom.xml

Do not shade org.w3c package

---

pom.xml

#421 adding generation of javadocs

---

webtau-reactjs/src/report/Report.js
webtau-reactjs/src/report/summary/OverallInfo.js
webtau-reactjs/src/report/summary/overal-info/TestsRanRatio.js
webtau-reactjs/src/test-data/testData.js

adds new section to report summary with ran ratio
also should close #382

add ran ratio vs skipped. adjust math.

---

webtau-reactjs/src/report/ReportComponentViewer.js
webtau-reactjs/src/report/details/http-header/CollapsibleHttpHeader.demo.js
webtau-reactjs/src/report/details/http-header/CollapsibleHttpHeader.js
webtau-reactjs/src/report/details/http-header/HttpHeader.css

report render guard for an empty http header

---

webtau-docs/webtau/generic-runners/JUnit-4.md
webtau-junit-like-examples-common/src/main/java/com/example/tests/junitlike/cfg/DynamicPortBaseUrlConfig.java
webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/CustomerCrudBeforeAfterGroovyTest.groovy
webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/CustomerCrudSingleGroovyTest.groovy
webtau-junit4-examples/src/test/java/com/example/tests/junit4/CustomerCrudBeforeAfterJavaTest.java
webtau-junit4-examples/src/test/java/com/example/tests/junit4/TodoListJavaIT.java
webtau-junit4-examples/src/test/java/com/example/tests/junit4/WeatherJavaIT.java
webtau-junit4/src/main/java/com/twosigma/webtau/junit4/WebTauRunner.java
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/CustomerCrudSeparatedGroovyTest.groovy
webtau-report/src/main/java/com/twosigma/webtau/report/ReportTestEntry.java

improved support for juni4 before/after + docs

---

pom.xml
webtau-junit5-examples/pom.xml
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/CustomerCrudSeparatedGroovyTest.groovy
webtau-junit5-examples/src/test/java/com/example/tests/junit5/CustomerCrudSeparatedJavaTest.java
webtau-junit5/pom.xml
webtau-junit5/src/main/java/com/twosigma/webtau/junit5/WebTauJunitExtension.java

Proper interception of `@BeforeAll` and `@AfterAll` using new jupiter extension mentioned here https://github.com/junit-team/junit5/issues/1769

use junit5 InvocationInterceptor to better support Before/AfterAll

---

webtau-reactjs/src/report/details/TestSteps.js
webtau-reactjs/src/report/details/steps/Steps.js

unique id for Step component instances to preserve 'collapse' status

---

webtau-core/src/main/java/com/twosigma/webtau/Matchers.java
webtau-core/src/test/java/com/twosigma/webtau/expectation/code/ThrowExceptionMatcherTest.java

follow up on @tsiq-clemens review

doc adjustments to Matchers class java doc

---

pom.xml
webtau-core/src/main/java/com/twosigma/webtau/Matchers.java
webtau-core/src/main/java/com/twosigma/webtau/data/traceable/TraceableValue.java

fix javadoc strings. enable javadoc build outside of release

---

pom.xml
webtau-json-schema/pom.xml
webtau-json-schema/src/main/java/com/twosigma/webtau/schema/expectation/SchemaMatcher.java
webtau-json-schema/src/test/groovy/com/twosigma/webtau/expectation/schema/SchemaMatcherTest.groovy
webtau-utils/src/main/java/com/twosigma/webtau/utils/JsonUtils.java

Closes #438.
The validation error messages have changed as a result of this but I doubt that would be an issue, I don't imagine anyone is programatically relying on those!

Switch json schema validator libraries

---

.travis.yml
pom.xml
webtau-feature-testing/examples/scenarios/rest/springboot/api-spec.json
webtau-feature-testing/examples/scenarios/rest/springboot/customerCrud.groovy
webtau-feature-testing/test-expectations/scenarios/rest/springboot/customerCrud/run-details.json
webtau-http-groovy/src/main/groovy/com/twosigma/webtau/http/HttpExtensions.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyOverloadsTest.groovy
webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
webtau-test-server/src/main/java/com/twosigma/webtau/http/testserver/TestServer.java
webtau-testapp/src/main/java/com/example/demo/springboot/app/data/CustomerController.java

add support for http patch

---

webtau-docs/webtau/REST/CRUD.md

document default statusCode checking behavior for the new PATCH method; it is the same as PUT and DELETE:
* 200 if there is a response body
* 204 if there is no response content

document default behavior for PATCH

---

webtau-report/src/main/java/com/twosigma/webtau/report/HtmlReportGenerator.java
webtau-shaded/pom.xml

fixes #471 
ran this locally to success against our complete suite

do not shade ivy and rhino

---

webtau-report-testing/src/test/groovy/pages/Report.groovy

should close #484 . 
@tsiq-karold could you please try this locally?

report ui test wait for report to render before assertions

---

pom.xml
webtau-core/src/main/java/com/twosigma/webtau/reporter/ConsoleTestListener.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/TestListener.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/TestListeners.java
webtau-core/src/main/java/com/twosigma/webtau/reporter/TestResultPayloadExtractorTestListener.java
webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauEndToEndTestRunner.groovy
webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy
webtau-junit5-examples/pom.xml
webtau-junit5/pom.xml
webtau-junit5/src/main/java/com/twosigma/webtau/junit5/WebTauJunitExtension.java
webtau-junit5/src/test/java/com/twosigma/webtau/junit5/WebTauJunitExtensionTest.groovy
webtau-junit5/src/test/java/com/twosigma/webtau/junit5/WithFailedPostStepTest.java
webtau-report/src/main/java/com/twosigma/webtau/report/ReportGeneratorTestListener.java
webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTest.groovy

This is a prerequisite to #488 so we can fail as part of a test using a `TestListener`

add beforeFirstTestStatement, afterLastTestStatement to TestListener

---

webtau-browser/src/main/java/com/twosigma/webtau/browser/documentation/BrowserDocumentation.java
webtau-feature-testing/examples/scenarios/ui/docCapture.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauBrowserFeaturesTest.groovy
webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauFeaturesManualTestServer.groovy
webtau-feature-testing/test-expectations/scenarios/ui/docCapture/run-details.json

implicit visibility check for doc.capture used elements

---

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/reporter/WebTauTestMetadataTest.groovy

add metadata access test

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/data/table/render/DefaultTableCellDataRenderer.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/data/table/render/TableCellDataRenderer.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/data/table/render/TableRenderer.java
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/repl/Repl.groovy
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/repl/tabledata/ReplTableCellDataRenderer.groovy
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/repl/tabledata/ReplTableRenderStyle.groovy
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/repl/tabledata/ReplTableRenderer.groovy
webtau-groovy/src/test/groovy/org/testingisdocumenting/webtau/cli/repl/tabledata/ReplTableRendererTest.groovy

colored repl table renderer with auto aligned csv look and feel

---

webtau-cli-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/CliExtension.groovy
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/Cli.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliDocumentation.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliValidationResult.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/expectation/CliExitCode.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/expectation/CliExitCodeCompareToHandler.java
webtau-cli/src/test/java/org/testingisdocumenting/webtau/cli/CliJavaTest.java
webtau-feature-testing/examples/scenarios/cli/implicitExitCodeCheck.groovy
webtau-feature-testing/scripts/exit-code
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauCliFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/cli/implicitExitCodeCheck/run-details.json
webtau-feature-testing/test-expectations/scenarios/cli/pathBasedScript/run-details.json
webtau-feature-testing/test-expectations/scenarios/cli/simpleRun/run-details.json

this and #534 (cli with no validation block) closes #405

cli exit code implicit check

---

webtau-http-groovy/src/main/groovy/org/testingisdocumenting/webtau/http/HttpExtensions.groovy
webtau-http-groovy/src/test/groovy/org/testingisdocumenting/webtau/http/HttpGroovyOverloadsTest.groovy
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/Http.java
webtau-http/src/test/java/org/testingisdocumenting/webtau/http/HttpJavaOverloadsTest.java
webtau-http/src/test/java/org/testingisdocumenting/webtau/http/HttpTestDataServer.java

addition http post and put overloads without validation

---

webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/BrowserConfig.java
webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/documentation/BrowserDocumentation.java
webtau-browser/src/test/groovy/org/testingisdocumenting/webtau/browser/documentation/BrowserDocumentationTest.groovy
webtau-browser/src/test/resources/test.html
webtau-cli-groovy/src/test/groovy/org/testingisdocumenting/webtau/cli/CliDocTest.groovy
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliDocumentation.java
webtau-cli/src/test/java/org/testingisdocumenting/webtau/cli/CliJavaTest.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/documentation/DocumentationArtifacts.java
webtau-feature-testing/examples/scenarios/rest/springboot/listMatchByKey.groovy
webtau-http-groovy/src/test/groovy/org/testingisdocumenting/webtau/http/HttpDocCaptureTest.groovy
webtau-http-groovy/src/test/groovy/org/testingisdocumenting/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/HttpDocumentation.java
webtau-report-testing/src/test/groovy/scenarios/cliDetails.groovy

doc capture: validate that artifact name is unique

---

webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/page/PageElementStepExecutor.java
webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/page/path/GenericPageElement.java
webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/page/value/handlers/CheckBoxGetSelValueHandler.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/TestStep.java
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/reporter/TestStepTest.groovy
webtau-filesystem/src/main/java/org/testingisdocumenting/webtau/fs/FileSystem.java
webtau-filesystem/src/test/groovy/org/testingisdocumenting/webtau/fs/FileSystemTest.groovy

core: test step completion message can use returned value

---

webtau-feature-testing/examples/scenarios/graphql/Report.groovy
webtau-feature-testing/examples/scenarios/graphql/queryAndMutation.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauGraphQLFeaturesTest.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauGraphQLFeaturesTestData.groovy
webtau-graphql/pom.xml
webtau-groovy/pom.xml
webtau-test-server/pom.xml
webtau-test-server/src/main/java/org/testingisdocumenting/webtau/http/testserver/GraphQLResponseHandler.java
webtau-utils/src/main/java/org/testingisdocumenting/webtau/utils/JsonUtils.java

In https://github.com/testingisdocumenting/webtau/pull/581, I forgot to add and update licenses in a few files.

Fix missing licenses

---

webtau-cli-testing/src/test/groovy/scenarios/repl.groovy
webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/IntegrationTestsMessageBuilder.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/Database.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseFacade.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseTable.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/LabeledDataSource.java
webtau-db/src/test/groovy/org/testingisdocumenting/webtau/db/DatabaseFacadeTest.groovy
webtau-feature-testing/test-expectations/scenarios/db/dbProviderThroughConfig/run-details.json

db: add test steps for update,query,insert

---

webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoverage.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchema.java
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLCoverageTest.groovy
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLSchemaTest.groovy
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/TestUtils.groovy

Filter out more things which aren't GraphQL queries from coverage recording.

graphql - more robust query processing

---

README.md
webtau-graphql-groovy/src/main/groovy/org/testingisdocumenting/webtau/graphql/GraphQLExtensions.groovy
webtau-graphql-groovy/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLGroovyOverloadsTest.groovy
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQL.java
webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLJavaOverloadsTest.java
webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestBase.java
webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestDataServer.java
webtau-test-server/src/main/java/org/testingisdocumenting/webtau/http/testserver/GraphQLResponseHandler.java

This wasn't at all tedious 😁 
Fixes #603

graphql: full set of execute overloads

---

webtau-docs/znai/UI/element-actions.md
webtau-docs/znai/toc
webtau-feature-testing/examples/scenarios/ui/elementActions.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauBrowserFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/ui/elementActions/run-details.json

browser: document page element actions

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/IntegrationTestsMessageBuilder.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/Database.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseCompareToHandler.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseFacade.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseQueryResult.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseTable.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/QueryRunnerUtils.java
webtau-db/src/main/resources/META-INF/services/org.testingisdocumenting.webtau.expectation.equality.CompareToHandler
webtau-db/src/test/groovy/org/testingisdocumenting/webtau/db/DatabaseBaseTest.groovy
webtau-db/src/test/groovy/org/testingisdocumenting/webtau/db/DatabaseFacadeTest.groovy
webtau-db/src/test/groovy/org/testingisdocumenting/webtau/db/DatabaseStepReporterTest.groovy
webtau-feature-testing/examples/scenarios/db/dbProviderThroughConfig.groovy

db: make query result comparison a test step

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/persona/Persona.java

For debugging it can be useful to log the persona.

core: add toString() to Persona

---

webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/TestUtils.groovy
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/Http.java
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/validation/HttpValidationResult.java
webtau-http/src/test/groovy/org/testingisdocumenting/webtau/http/HttpValidationResultTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiCoverageTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidatorTest.groovy
webtau-reactjs/src/report/details/http/TestHttpCalls.js
webtau-reactjs/src/test-data/testData.js

persona: add persona column to http calls tab

---

pom.xml
webtau-docs/pom.xml
webtau-feature-testing/examples/scenarios/rest/openapi/openApiHttpSpec.groovy
webtau-feature-testing/examples/scenarios/rest/openapi/webtau.httpspec.cfg.groovy
webtau-feature-testing/pom.xml
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauRestFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/rest/openapi/openApiHttpSpec/run-details.json
webtau-junit4-examples/pom.xml
webtau-junit5-examples/pom.xml
webtau-open-api/pom.xml
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApi.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpec.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecConfig.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidator.java
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidatorTest.groovy
webtau-open-api/src/test/resources/test-spec.json
webtau-testapp/pom.xml
webtau-testapp/src/main/java/com/example/demo/springboot/app/SpringBootDemoApp.java

open-api: add v3; add spec from http

---

webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliBackgroundCommandManager.java

currently registration can be triggered as the shutdown hook is being executed (junit4 at the end of all tests).

cli: lazy register shutdown hook

---

webtau-docs/znai/UI/basic-configuration.md

browser: add browserId docs

---

webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoveredQueries.java
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProviderTest.groovy

graphql: make coverage recording thread safe

---

webtau-graphql-groovy/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLListenersTest.groovy
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQL.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoverage.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchema.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchemaLoader.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/listener/GraphQLListener.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/listener/GraphQLListeners.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/model/GraphQLRequest.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/model/GraphQLResponse.java
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLSchemaTest.groovy
webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestBase.java
webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestDataServer.java
webtau-graphql/src/test/resources/test-schema.graphql
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cfg/WebTauGroovyFileConfigHandler.groovy

graphql: graphql listener

---

webtau-docs/pre-filter/installation-groovy-runner.md

```
brew install testingisdocumenting/brew/webtau
```

documentation: add brew install

---

webtau-http/src/main/java/org/testingisdocumenting/webtau/http/HttpHeader.java
webtau-http/src/test/groovy/org/testingisdocumenting/webtau/http/HttpHeaderTest.groovy

fixes https://github.com/testingisdocumenting/webtau/issues/785

fix NPE on get

---

pom.xml
webtau-docs/znai/GraphQL/customized-graphql-urls.md
webtau-docs/znai/GraphQL/introduction.md
webtau-docs/znai/lookup-paths
webtau-docs/znai/toc
webtau-graphql-groovy/src/test/groovy/org/testingisdocumenting/webtau/graphql/CustomGraphQLHttpConfiguration.groovy
webtau-graphql-groovy/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLHttpConfigurationsTest.groovy
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQL.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/config/GraphQLHttpConfiguration.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/config/GraphQLHttpConfigurations.java
webtau-test-server/src/main/java/org/testingisdocumenting/webtau/http/testserver/GraphQLResponseHandler.java

fixes https://github.com/testingisdocumenting/webtau/issues/773

graphql: custom GraphQLHttpConfiguration

---

webtau-docs/znai/GraphQL/customized-graphql-urls.md
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/ConfigBasedGraphQLHttpConfiguration.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLConfig.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/config/GraphQLHttpConfiguration.java
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/config/GraphQLHttpConfigurations.java
webtau-graphql/src/main/resources/META-INF/services/org.testingisdocumenting.webtau.graphql.config.GraphQLHttpConfiguration
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/ConfigBasedGraphQLHttpConfigurationTest.groovy

completes implementation for https://github.com/testingisdocumenting/webtau/issues/773

graphql: add config for graphqlEndpoint, showGraphqlOperationAsQueryParam

---

webtau-docs/znai/groovy-standalone-runner/skipping-tests.md
webtau-feature-testing/examples/scenarios/concept/conditionalEnvRegistrationRun.groovy
webtau-feature-testing/examples/scenarios/concept/conditionalEnvRegistrationSkip.groovy
webtau-feature-testing/test-expectations/scenarios/concept/conditionalEnvRegistrationRun/run-details.json
webtau-feature-testing/test-expectations/scenarios/concept/conditionalEnvRegistrationSkip/run-details.json
webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/WebTauGroovyDsl.groovy

After adding this for the 3rd project in a row, I think it is useful in webtau itself.

groovy: add skipForEnv convenience DSL

---

.gitignore

dealing with a few files that tend to hang around and confuse me when I prep commits

build: git: ignore runtime-generated test files

---

webtau-core-groovy/src/test/groovy/org/testingisdocumenting/webtau/persona/PersonaExtensionsTest.groovy
webtau-core/src/main/java/org/testingisdocumenting/webtau/persona/Persona.java
webtau-core/src/test/java/org/testingisdocumenting/webtau/persona/PersonaTest.java

allow nesting of the already active persona

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/handlers/IterableAndTableDataCompareToHandler.java
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/expectation/equality/handlers/IterableAndTableDataCompareToHandlerTest.groovy

matchers: set and table data compareTo handler fix

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/time/Time.java
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/reporter/ConsoleStepReporterTest.groovy
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/time/ControlledTimeProvider.groovy
webtau-http-groovy/pom.xml
webtau-http-groovy/src/test/groovy/org/testingisdocumenting/webtau/http/HttpGroovyTest.groovy
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/Http.java
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/validation/HttpValidationResult.java

http: capture start/elapsed of failed http call

---

webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/documentation/BrowserDocumentation.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliDocumentation.java
webtau-feature-testing/test-expectations/scenarios/cli/basicLs/run-details.json
webtau-feature-testing/test-expectations/scenarios/ui/docCapture/chrome-run-details.json
webtau-feature-testing/test-expectations/scenarios/ui/docCapture/firefox-run-details.json

Browser and cli doc step

---

webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliConfig.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/ProcessUtils.java
webtau-cli/src/main/resources/META-INF/services/org.testingisdocumenting.webtau.cfg.WebTauConfigHandler
webtau-cli/src/test/java/org/testingisdocumenting/webtau/cli/CliJavaTest.java
webtau-config/src/main/java/org/testingisdocumenting/webtau/cfg/WebTauConfig.java
webtau-docs/znai/cli/background-command.md
webtau-docs/znai/cli/foreground-command.md
webtau-feature-testing/examples/scenarios/cli/cliBackgroundRunConfig.groovy
webtau-feature-testing/examples/scenarios/cli/pathBasedScript.groovy
webtau-feature-testing/examples/scenarios/cli/webtau-with-path.cfg.groovy
webtau-feature-testing/scripts/sleeps
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauCliFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/cli/cliBackgroundRunConfig/run-details.json
webtau-feature-testing/test-expectations/scenarios/cli/pathBasedScript/run-details.json
webtau-groovy/src/test/groovy/org/testingisdocumenting/webtau/cfg/CLIArgsTest.groovy

closes #369 
@tsiq-karold note the path config parameter change, It wasn't documented before. It is backward incompatible if you used it already.

cli: envPath -> cliPath config rename + docs

---

webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliBackgroundProcess.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliConfig.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/ProcessUtils.java
webtau-cli/src/test/java/org/testingisdocumenting/webtau/cli/CliJavaTest.java
webtau-config/src/main/java/org/testingisdocumenting/webtau/cfg/ConfigValue.java
webtau-docs/znai/cli/foreground-command.md
webtau-feature-testing/examples/scenarios/cli/cliTimeout.groovy
webtau-feature-testing/examples/scenarios/cli/webtau-cli-timeout.cfg.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauCliFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/cli/cliTimeout/run-details.json

cli: timeout handling and config

---

webtau-db/src/main/java/org/testingisdocumenting/webtau/db/Database.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseFacade.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DatabaseTable.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/DbQuery.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/LabeledDataSourceCachedProvider.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/LabeledDataSourceProvider.java
webtau-db/src/main/java/org/testingisdocumenting/webtau/db/QueryRunnerUtils.java
webtau-feature-testing/examples/scenarios/db/lazyQuery.groovy
webtau-feature-testing/examples/scenarios/db/webtau-wrong-db-primary.cfg.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauDbFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/db/lazyQuery/run-details.json

@tsiq-karold please review.
I will extract lazy-init common one in a separate PR and will use in other places

db: lazy primary datasource init

---

webtau-docs/pre-filter/installation-groovy-runner.md

@motlin @tsiq-clemens @tsiq-karold 
FYI - Webtau is on sdkman now!

docs: sdkman install instructions

---

webtau-feature-testing/test-expectations/scenarios/rest/openapi/disableOpenApiValidation/run-details.json
webtau-feature-testing/test-expectations/scenarios/rest/openapi/openApiHttpSpec/run-details.json
webtau-feature-testing/test-expectations/scenarios/rest/springboot/checkExistingServerIsStillUp/run-details.json
webtau-feature-testing/test-expectations/scenarios/rest/springboot/customerCrudSeparatedMissingMethod/run-details.json
webtau-feature-testing/test-expectations/scenarios/rest/springboot/startAndStopAsPartOfSuite/run-details.json
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpec.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecConfig.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecLocation.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidator.java
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiCoverageTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiResponseValidatorTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiSpecTest.groovy
webtau-open-api/src/test/groovy/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidatorTest.groovy

http: read openapi with http.get to respect auth handlers

---

webtau-console/src/main/java/org/testingisdocumenting/webtau/console/ansi/Color.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/ConsoleTestListener.java

groovy runner: scenario start distinct color

---

webtau-reactjs/src/report/Report.js
webtau-reactjs/src/report/summary/EnvVarsTable.css
webtau-reactjs/src/report/summary/EnvVarsTable.tsx
webtau-reactjs/src/report/summary/OverallSummary.js
webtau-reactjs/src/test-data/testData.js
webtau-report-testing/pom.xml
webtau-report-testing/src/test/groovy/pages/Report.groovy
webtau-report-testing/src/test/groovy/scenarios/summaryOverview.groovy
webtau-report/src/main/java/org/testingisdocumenting/webtau/report/HtmlReportGenerator.java

report: add env vars section

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/WebTauReport.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/WebTauReportCustomData.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/WebTauReportLog.java
webtau-feature-testing/examples/scenarios/graphql/Report.groovy
webtau-feature-testing/examples/scenarios/graphql/TestReport.groovy
webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProvider.java
webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProviderTest.groovy
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/perf/HttpPerformanceValidationHandler.java
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/report/HttpCallsReportDataProvider.java
webtau-http/src/test/groovy/org/testingisdocumenting/webtau/http/report/HttpCallsReportDataProviderTest.groovy
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiReportDataProvider.java
webtau-report/src/main/java/org/testingisdocumenting/webtau/report/HtmlReportGenerator.java
webtau-report/src/main/java/org/testingisdocumenting/webtau/report/ReportDataProviders.java
webtau-report/src/main/java/org/testingisdocumenting/webtau/report/ReportGenerators.java
webtau-report/src/main/java/org/testingisdocumenting/webtau/report/perf/PerformanceReport.java

report: add a way to register errors during report data gen

---

webtau-reactjs/src/report/Report.js
webtau-reactjs/src/report/WebTauReport.js
webtau-reactjs/src/report/summary/OverallHttpPerformance.tsx
webtau-reactjs/src/report/summary/OverallSummary.js
webtau-reactjs/src/report/summary/TestsPerformance.tsx

report: add tests performance

---

webtau-feature-testing/examples/scenarios/rest/openapi/not-full-spec.json
webtau-feature-testing/examples/scenarios/rest/openapi/unspecifiedUrl.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauRestFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/rest/openapi/unspecifiedUrl/run-details.json
webtau-http/src/main/java/org/testingisdocumenting/webtau/http/validation/HttpValidationResult.java
webtau-http/src/test/groovy/org/testingisdocumenting/webtau/http/HttpValidationResultTest.groovy
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecLocation.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiSpecValidator.java
webtau-reactjs/src/report/WebTauReport.css
webtau-reactjs/src/report/details/SourceCode.js
webtau-reactjs/src/report/details/TestNameCard.js
webtau-reactjs/src/report/details/TestSummary.css
webtau-reactjs/src/report/details/TestSummary.js
webtau-reactjs/src/report/details/cli/CliCommandCard.js
webtau-reactjs/src/report/details/cli/CliOutputCard.js
webtau-reactjs/src/report/details/http/HttpCallDetails.js
webtau-reactjs/src/report/details/steps/Step.tsx
webtau-reactjs/src/report/summary/PercentilePerformanceDiagram.js
webtau-reactjs/src/report/widgets/Card.css
webtau-reactjs/src/report/widgets/Card.tsx
webtau-reactjs/src/report/widgets/CardWithElapsedTime.js
webtau-reactjs/src/report/widgets/CardWithPadding.js
webtau-reactjs/src/report/widgets/CardWithTime.js
webtau-reactjs/src/test-data/testData.js
webtau-report-testing/src/test/groovy/pages/Report.groovy
webtau-report-testing/src/test/groovy/scenarios/warnings.groovy

http: capture openapi warning in web report

---

webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/Cli.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliProcessConfig.java
webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/ProcessUtils.java
webtau-docs/znai/cli/foreground-command.md
webtau-feature-testing/examples/scenarios/cli/cliTimeoutLocalOverride.groovy
webtau-feature-testing/examples/scenarios/cli/webtau-cli-timeout-large.cfg.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauCliFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/cli/cliTimeoutLocalOverride/run-details.json

cli: local timeout override

---

webtau-cli-testing/src/test/groovy/scenarios/replTestDisabledAndSingleTestSelection.groovy
webtau-cli-testing/src/test/groovy/testscripts/disabledAndSingleScenarios.groovy
webtau-docs/znai/release-notes/1.43/add-2021-07-18-repl-ignore-disabled-and-single-scenario.md
webtau-standalone-runner-groovy/src/main/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTestRunner.groovy

repl: ignore dscenario and sscenario in repl mode

---

webtau-docs/znai/release-notes/1.45/_fix-2021-12-23-open-api-coverage-trigger.md
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApi.java
webtau-open-api/src/main/java/org/testingisdocumenting/webtau/openapi/OpenApiReportDataProvider.java

openapi: stop call to fetch api schema at the end if no http calls 

---

webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/BrowserCookies.java
webtau-browser/src/main/java/org/testingisdocumenting/webtau/browser/BrowserLocalStorage.java
webtau-docs/znai/release-notes/1.48/fix-2022-05-17-cookie-storage-java-access.md
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/WebTauFeaturesJUnit5Test.groovy
webtau-junit5-examples/src/test/java/com/example/tests/junit5/BrowserCookieJavaTest.java
webtau-junit5-examples/src/test/java/com/example/tests/junit5/BrowserLocalStorageJavaTest.java
webtau-junit5-examples/src/test/java/com/example/tests/junit5/WeatherJavaTest.java
webtau-junit5-examples/test-expectations/BrowserCookieJavaTest/run-details.json
webtau-junit5-examples/test-expectations/BrowserLocalStorageJavaTest/run-details.json

browser: fix java access to cookies and storage

---

webtau-docs/znai/groovy-standalone-runner/skipping-tests.md
webtau-docs/znai/release-notes/1.48/add-2022-05-19-disable-by-file-name.md
webtau-feature-testing/examples/scenarios/concept/skipTestsByFileName.disabled.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauConceptFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/concept/skipTestsByFileName/run-details.json
webtau-standalone-runner-groovy/src/main/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTestRunner.groovy

groovyrunner: disable tests by file name convention

---

webtau-core-groovy/src/test/groovy/org/testingisdocumenting/webtau/MatchersGroovyTest.groovy
webtau-core-groovy/src/test/groovy/org/testingisdocumenting/webtau/expectation/equality/handlers/DatesCompareToHandlerGroovyExamplesTest.groovy
webtau-core/src/main/java/org/testingisdocumenting/webtau/Matchers.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/ActualPathMessage.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/AnyOfMatcher.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/handlers/ValueMatcherCompareToHandler.java
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/expectation/equality/AnyOfMatcherTest.groovy
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/expectation/equality/handlers/ValueMatcherCompareToHandlerTest.groovy
webtau-core/src/test/java/org/testingisdocumenting/webtau/MatchersTest.java
webtau-core/src/test/java/org/testingisdocumenting/webtau/expectation/equality/handlers/DatesCompareToHandlerJavaExamplesTest.java
webtau-docs/znai/matchers/any-of.md
webtau-docs/znai/matchers/static-import.md
webtau-docs/znai/matchers/universal-compare.md
webtau-docs/znai/release-notes/1.49/add-2022-06-08-any-of-matcher.md
webtau-docs/znai/toc

matchers: add anyOf matcher

---

webtau-cache/src/main/java/org/testingisdocumenting/webtau/cache/Cache.java
webtau-cache/src/main/java/org/testingisdocumenting/webtau/cache/FileBasedCache.java
webtau-docs/znai/release-notes/1.50/add-2022-08-20-cache-expired-value.md
webtau-docs/znai/release-notes/2022.md
webtau-docs/znai/utilities/cache.md
webtau-feature-testing/examples/scenarios/cache/cachedExpirationValue.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauCacheFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/cache/cachedExpirationValue/run-details.json

cache: get with expiration

---

webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/handlers/IterableAndTableDataCompareToHandler.java
webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/handlers/TableDataCompareToHandler.java
webtau-core/src/test/groovy/org/testingisdocumenting/webtau/expectation/equality/handlers/IterableAndTableDataCompareToHandlerTest.groovy
webtau-docs/znai/release-notes/1.50/add-2022-11-07-list-of-maps-table-fix.md

tabledata: properly report missing columns when compared with maps

---

webtau-docs/znai/release-notes/2.1/add-2023-06-17-fake-server-request-query.md
webtau-docs/znai/release-notes/2.1/fix-2023-06-17-fake-server-request-full-url.md
webtau-docs/znai/release-notes/2023.md
webtau-feature-testing/examples/scenarios/server/proxyServer.groovy
webtau-junit5-examples/src/test/java/com/example/tests/junit5/FakeServerJavaTest.java
webtau-junit5-examples/test-expectations/FakeServerJavaTest/run-details.json
webtau-server/src/main/java/org/testingisdocumenting/webtau/server/WebTauServerRequest.java

servers: expose query string

---

webtau-docs/znai/release-notes/2.1/add-2023-06-22-server-router-query-param.md
webtau-docs/znai/servers/server-router.md
webtau-docs/znai/toc
webtau-feature-testing/examples/scenarios/server/router.groovy
webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauServerFeaturesTest.groovy
webtau-feature-testing/test-expectations/scenarios/server/router/run-details.json
webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/JUnit4FeatureTestRunner.groovy
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/JUnit5FeatureTestRunner.groovy
webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/WebTauFeaturesJUnit5Test.groovy
webtau-junit5-examples/src/test/java/com/example/tests/junit5/FakeServerJavaTest.java
webtau-junit5-examples/src/test/java/com/example/tests/junit5/RouterPropertiesJavaTest.java
webtau-junit5-examples/test-expectations/FakeServerJavaTest/run-details.json
webtau-junit5-examples/test-expectations/RouterPropertiesJavaTest/run-details.json
webtau-server/src/main/java/org/testingisdocumenting/webtau/server/QueryParamsParser.java
webtau-server/src/main/java/org/testingisdocumenting/webtau/server/WebTauServerFacade.java
webtau-server/src/main/java/org/testingisdocumenting/webtau/server/WebTauServerRequest.java
webtau-server/src/test/groovy/org/testingisdocumenting/webtau/server/QueryParamsParserTest.groovy

server: expose router request.queryParam
