testingisdocumenting/webtau

webtau-core/src/main/java/com/twosigma/webtau/reporter/StepReporter.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/StepsTestResultPayloadExtractor.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/TestResultPayloadExtractor.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/TestResultPayloadExtractors.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/TestStep.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/ValueMatcherExpectationSteps.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/stacktrace/StackTraceUtils.java, webtau-core/src/test/groovy/com/twosigma/webtau/reporter/TestStepTest.groovy, webtau-reactjs/src/report/Report.js, webtau-reactjs/src/report/WebTauReport.css, webtau-reactjs/src/report/details/Steps.css, webtau-reactjs/src/report/details/http/HttpCallDetails.css, webtau-reactjs/src/report/details/http/HttpCallDetails.js, webtau-reactjs/src/report/details/http/TestHttpCalls.css, webtau-reactjs/src/report/details/http/TestHttpCalls.js, webtau-report/src/main/java/com/twosigma/webtau/report/ReportTestEntry.java, webtau-rest-groovy/src/test/groovy/com/twosigma/webtau/http/HttpTest.groovy, webtau-rest/src/main/java/com/twosigma/webtau/http/Http.java, webtau-rest/src/main/java/com/twosigma/webtau/http/HttpCallsTestResultPayloadExtractor.java, webtau-rest/src/main/java/com/twosigma/webtau/http/HttpException.java, webtau-rest/src/main/java/com/twosigma/webtau/http/HttpValidationResult.java, webtau-rest/src/test/groovy/com/twosigma/webtau/http/HttpValidationResultTest.groovy, webtau-rest/src/test/groovy/com/twosigma/webtau/http/OpenAPISpecValidatorTest.groovy, webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTest.groovy, webtau/src/main/java/com/twosigma/webtau/WebTauDsl.java, webtau/src/main/java/com/twosigma/webtau/reporter/ScreenshotStepReporter.java, webtau/src/main/java/com/twosigma/webtau/reporter/ScreenshotTestResultPayloadExtractor.java
Report is now able to show/distinct http calls with error (e.g. wrong url protocol).
TestStep refactoring.
=> capture http call related errors

webtau-groovy/src/main/groovy/com/twosigma/webtau/data/LazyTestResource.groovy
This will allow access to the entire contained object, not just individual properties.
=> get() method on lazy test resource

webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/CliReportGenerator.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy, webtau-groovy/src/main/resources/META-INF/services/com.twosigma.webtau.report.ReportGenerator, webtau-groovy/src/test/groovy/com/twosigma/webtau/WebtauFeaturesTesting.groovy, webtau-report/src/main/java/com/twosigma/webtau/report/ReportTestEntries.java, webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTest.groovy, webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/report/StandardConsoleTestListener.groovy, webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
stop printing stacktraces for each test during test run
and instead printing failed stacktraces at the end
=> print failed and errored tests at the end

pom.xml, webtau-core-groovy/pom.xml, webtau-groovy-ast/pom.xml, webtau-groovy/pom.xml, webtau-http-groovy/pom.xml, webtau-standalone-runner-groovy/pom.xml
Stubs generation is messing IDEA. They were generated to generate javadocs for maven central. 
Instead we generate docs using gmaven-plus:groovydoc and point to a location that java expects.
=> replace groovyJavaStubs with groovydoc. add implicit groovy profile

pom.xml, webtau-maven-plugin-test-skip/pom.xml, webtau-maven-plugin-test-skip/src/tests/groovy/scenarios/featureA.groovy, webtau-maven-plugin-test-skip/src/tests/groovy/webtau.cfg, webtau-maven-plugin/src/main/groovy/com/twosigma/webtau/maven/WebTauMavenRunner.groovy, webtau-open-api/src/main/java/com/twosigma/webtau/openapi/OpenApiSpecConfig.java
This is based on the surefire plugin behaviour: http://maven.apache.org/plugins-archives/maven-surefire-plugin-2.12.4/examples/skipping-test.html and code: https://github.com/apache/maven-surefire/blob/7149edc6f24fa8bff06372e24a177e86d4960d8c/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L177
It started off as just adding the skip tests capability and a test for it but found a couple of issues I had to fix:
1. the maven plugin test was not actually executing the tests because it requires the execution part to be set up.  I think there is a way to make that work by default but I don't remember off the top of my head what that is
1. adding a fix for the above unearthed a bug in the OpenAPISpec loading which resulted in an exception being …
=> Maven plugin to respect skipTests

webtau-docs/webtau/REST/headers.md, webtau-http-groovy/src/main/groovy/com/twosigma/webtau/http/HttpExtensions.groovy, webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpTest.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java, webtau-http/src/main/java/com/twosigma/webtau/http/multipart/MultiPartFormData.java, webtau-http/src/main/java/com/twosigma/webtau/http/request/EmptyRequestBody.java, webtau-http/src/main/java/com/twosigma/webtau/http/request/HttpApplicationMime.java, webtau-http/src/main/java/com/twosigma/webtau/http/request/HttpQueryParams.java, webtau-http/src/main/java/com/twosigma/webtau/http/request/HttpRequestBody.java, webtau-http/src/main/java/com/twosigma/webtau/http/request/HttpTextMime.java, webtau-http/src/main/java/com/twosigma/webtau/http/text/TextRequestBody.java, webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationResult.java, webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpValidationResultTest.groovy
this hopefully help to freeze API and move us closer to 1.0 and stable API.
Note: this PR is not backward compatible and existing tests that send byte[] directly need to change to
`http.application.octetStream(byte[])`
=> add mime type combined with request payload syntax + docs

webtau-reactjs/src/report/details/http-header/HttpHeader.css, webtau-reactjs/src/report/details/http-header/HttpHeader.js, webtau-reactjs/src/test-data/testData.js
=> break long http header key in report. use monospace for key

webtau-docs/webtau/groovy-specific-runner/selective-run.md, webtau-docs/webtau/groovy-specific-runner/skipping-tests.md, webtau-docs/webtau/toc, webtau-feature-testing/examples/scenarios/concept/runOnlySelected.groovy, webtau-feature-testing/examples/scenarios/concept/skipTests.groovy, webtau-feature-testing/src/test/groovy/com/twosigma/webtau/featuretesting/WebTauConceptFeaturesTest.groovy, webtau-feature-testing/test-expectations/scenarios/concept/runOnlySelected/run-details.json, webtau-feature-testing/test-expectations/scenarios/concept/skipTests/run-details.json, webtau-groovy/src/main/groovy/com/twosigma/webtau/WebTauGroovyDsl.groovy
A few changes in this PR:
- adding `singleScenario` and `disabledScenario` as aliases for `sscenario` and `dscenario` respectively.  This is to aid readability but still allow conciseness if desired
- adding `dscenario` to documentation.  I highjacked and renamed the selective skipping chapter for this.  Feel free to disagree with that move
- fixing a bug with `dscenario` and test runners where it would invoke the scenario anyway.  Should check what happens in interactive mode though because I think we should execute it if someone runs the disabled scenario explicitly but not if someone runs the entire file
=> Verbose DSL scenario names

webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/handlers/SetCompareToHandler.java, webtau-core/src/main/resources/META-INF/services/com.twosigma.webtau.expectation.equality.CompareToHandler, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/IterableCompareToHandlerTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/SetCompareToHandlerTest.groovy
Closes #209.
Set comparison complexity is going to be O(NM). In this PR set contains is not used and instead equality is checked by CompareToComparator to handle cases like
```
def actual = ['hello', 'world'] as Set
actual.should == [~/wo..d/, ~/h...o/] as Set
```
=> set compare to handler

pom.xml, webtau-config/pom.xml, webtau-console/pom.xml, webtau-core-groovy/pom.xml, webtau-core/pom.xml, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/HandlerMessagesTest.groovy, webtau-groovy-ast/pom.xml, webtau-http-groovy/pom.xml, webtau-json-schema/pom.xml, webtau-open-api/pom.xml, webtau-pdf/pom.xml, webtau-report/pom.xml, webtau-standalone-runner-groovy/pom.xml, webtau-test-server/pom.xml, webtau-utils/pom.xml
Fixes #203 .  Also reverted changes made in #204 as Groovy 2.5 fixes the underlying bug that had forced that change in the first place.  I have tested that webtau compiles and tests pass with Java 9.
Unfortunately, Groovy made a change to its packaging such that groovy-all no longer includes a fat jar.  To pull down all the necessary dependencies, we use its pom but that pulls in test modules which pull in junit so we have to exclude that.
I have also run all my tests against a local build of this PR.
=> Upgrade to Groovy 2.5

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/groovy/ast/ShouldAstTransformationTest.groovy, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/CompareToHandler.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/EqualMatcher.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/GreaterThanMatcher.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/GreaterThanOrEqualMatcher.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/LessThanMatcher.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/LessThanOrEqualMatcher.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/handlers/NullCompareToHandler.java, webtau-core/src/main/java/com/twosigma/webtau/expectation/equality/handlers/NumbersCompareToHandler.java, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/ActualValueTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/EqualMatcherTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/GreaterThanMatcherTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/GreaterThanOrEqualMatcherTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/LessThanMatcherTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/LessThanOrEqualMatcherTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/DateAndStringCompareToHandlerTest.groovy, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/equality/handlers/NullCompareToHandlerTest.groovy, webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy, webtau-http/src/test/groovy/com/twosigma/webtau/http/datanode/StructuredDataNodeTest.groovy, webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
This closes #259.
Since we are more precise in mismatch reporting now, Equal and Greater/Less Matchers do not provide summary text in case of mismatch anymore. Instead they solely rely on the generated Comparator mismatch report. 
Main motivation for the change is comparisons like `(null|value).shouldBe > (number|null)`. Matcher would provide additional message like "null is less than number" which would be inaccurate in case of nulls.
=> NullCompareTo handler deals with greater-less. Modify mismatch messages.

pom.xml, webtau-browser/pom.xml
The current wdm version (3.0.0) has no mapping for later versions of chrome and defaults to the latest chromedriver v74, which at this time is only compatible with a dev version of Chrome, and does not match the installed version (73).
This latest version pulls the correct version matching the installed chrome version.
=> update webdrivermanager to 3.4.0

webtau-core-groovy/src/test/groovy/com/twosigma/webtau/data/table/TableDataExtensionTest.groovy, webtau-core/src/main/java/com/twosigma/webtau/Ddjt.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/Record.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/TableData.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/TableDataCellMapFunction.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/autogen/TableDataCellValueGenFullFunction.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/autogen/TableDataCellValueGenFunctions.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/autogen/TableDataCellValueGenOnlyRecordFunction.java, webtau-core/src/main/java/com/twosigma/webtau/data/table/autogen/TableDataCellValueGenerator.java, webtau-core/src/test/groovy/com/twosigma/webtau/data/table/TableDataTest.groovy, webtau-core/src/test/java/com/twosigma/webtau/data/table/TableDataJavaSyntaxTest.java, webtau-core/src/test/java/com/twosigma/webtau/data/table/TableDataJavaTest.java, webtau-docs/webtau/reference/table-data.md
Initial functionality to allow the following.
```
["Col A" | "Col B" | "Col C"] {
__________________________________________
"v1a" |   "v1b" | 10
"v2a" |   "v2b" | cell.above
"v2a" |   "v2b" | cell.above + 10 }
```
It is not feature complete yet but want us to settle on names and approach.  
Most likely `__` shortcut will be added to mean the same as `cell.above`
=> add cell.above to refer to previous row value

webtau-core/src/main/java/com/twosigma/webtau/expectation/code/ThrowExceptionMatcher.java, webtau-core/src/test/groovy/com/twosigma/webtau/expectation/code/ThrowExceptionMatcherGroovyTest.groovy, webtau-docs/webtau/generic-runners/JUnit-5.md, webtau-docs/webtau/groovy-specific-runner/data-driven-scenarios.md
Some code flows involve a proxy that wrap checked exceptions in an UndeclaredThrowableException (see https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/reflect/UndeclaredThrowableException.html) .
In this case, we still need to extract the wrapped exception class and message.
=> Undeclared throwable

webtau-http/src/main/java/com/twosigma/webtau/http/HttpHeader.java, webtau-http/src/main/java/com/twosigma/webtau/http/HttpResponse.java, webtau-http/src/test/groovy/com/twosigma/webtau/http/HttpHeaderTest.groovy
Closes #332 
We can't really change the `add` method into a non-mutating version as it might break people.  Therefore, I've deprecated it and added a non-mutating `with`.
=> Adding with method to HttpHeader

pom.xml, webtau-config/src/main/java/com/twosigma/webtau/cfg/ConfigValue.java, webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java, webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java
Closes #329 
Default behaviour is to send `webtau/<version>`.  If a user agent is specified in cfg, we send `<cfg-user-agent> (webtau/<version>)`.  It is also possible to not append the `(webtau/<version>)` bit with a custom agent by specifying an appropriate cfg option.
=> Send user agent

webtau-http-groovy/src/main/groovy/com/twosigma/webtau/http/HttpExtensions.groovy, webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java, webtau-http/src/test/java/com/twosigma/webtau/http/HttpTestDataServer.java
closes #327 
PUT and DELETE don't support query params but this was so tedious for POST alone that I decided not to tackle PUT and DELETE yet, have raised issues for those: #335 and #336
=> add query param overloads for post requests

webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java, webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauMeta.java, webtau-core/pom.xml, webtau-core/src/main/resources/webtau.version, webtau-feature-testing/examples/scenarios/rest/openapi/api-spec.json, webtau-feature-testing/test-expectations/scenarios/rest/openapi/disableOpenApiValidation/run-details.json, webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauCliArgsConfig.groovy, webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/HttpGroovyTest.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java, webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationHandlers.java, webtau-report/src/main/java/com/twosigma/webtau/report/HtmlReportGenerator.java
Closes #302 
Before merging this, I'd like some feedback.  Prior to this PR, any `HttpValidationHandler` errors are reported even if status code fails or user expectations fail.  This is confusing in the case where you expect a request to succeed but it fails and the failure response is of a different schema to what you'd expect; it's confusing because you get a schema validation failure and the fact the request failed is not reported.
We have two options.  The behaviour this PR introduces is to only run `HttpValidationHandlers` if everything else is fine.  So generally you'll get a status code error or user expectation error and only if both of those are fine will you get a schema error.
Do you think it would be better to report in this order:
1. status code mismatch
1. schema failures …
=> Report status code before schema

pom.xml, webtau-cache/pom.xml, webtau-cli-groovy/pom.xml, webtau-cli-groovy/src/main/groovy/com/twosigma/webtau/cli/CliExtension.groovy, webtau-cli/pom.xml, webtau-cli/scripts/hello, webtau-cli/src/main/java/com/twosigma/webtau/cli/Cli.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/CliOutputListener.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/ProcessEnv.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/ProcessRunResult.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/ProcessUtils.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/StreamGobbler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliExitCode.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliExitCodeCompareToHandler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliOutput.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliOutputCompareToHandler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliOutputContainHandler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliResultExpectations.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliSetupAndValidationFullHandler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliValidationExitCodeOutputHandler.java, webtau-cli/src/main/java/com/twosigma/webtau/cli/expectation/CliValidationOutputOnlylHandler.java, webtau-cli/src/main/resources/META-INF/services/com.twosigma.webtau.expectation.contain.ContainHandler, webtau-cli/src/main/resources/META-INF/services/com.twosigma.webtau.expectation.equality.CompareToHandler, webtau-cli/src/test/java/com/twosigma/webtau/cli/CliJavaTest.java, webtau-cli/src/test/java/com/twosigma/webtau/cli/CliTestUtils.java, webtau-core/pom.xml, webtau-http-groovy/pom.xml, webtau-junit5-examples/pom.xml, webtau-junit5-examples/src/test/groovy/com/example/tests/junit5/DynamicTestsGroovyTest.groovy, webtau-junit5-groovy/pom.xml
Initial DSL for cli testing. Not exposed through `WebTauDsl` yet.  `CliJavaTest` shows basic java syntax. Approach is similar to `Http.`. 
It is most likely going to change so considering it is a private API for now. Want to put it out there so we can start conversation around. 
One of the syntax I want to be able to achieve follows
```
cli.run('command...') {
on('partial match') {
http.get( ... ) { 
}
}
onOptional('partial match') {
http.del(....) {
}
}
output.should contain('blah')
}
```
Alternatively we may try to use `waitTo` (not really sure how to approach this)
```
cli.run('command...') {
line.waitTo == ~/partial match/ 
http.get( ... ) { 
}
output.should contain('blah')
}
```
=> initial cli testing frame

webtau-docs/webtau/REST/test-execution.md, webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyCliArgsConfigHandler.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy, webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/RegisteredTests.groovy, webtau-standalone-runner-groovy/src/main/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunner.groovy, webtau-standalone-runner-groovy/src/test/groovy/com/twosigma/webtau/runner/standalone/StandaloneTestRunnerTest.groovy
Fixes #195
This PR does two things:
1. cap the size of the thread pool to the number of files.  i.e. if someone specifies 10 threads but there are only 2 files, we'll only create 2 threads.
1. provide a shortcut for saying use as many threads as we have files.  I've used -1 to indicate this though I'm not 100% happy about that.  Having said that, I don't really want to introduce another flag to indicate that's what we want because the interaction between the two configs might be a little confusing.  Thoughts welcome.
=> Shortcuts and sanity checks for number of threads config

webtau-docs/webtau/REST/getting-started.md, webtau-docs/webtau/UI/getting-started.md
This is to allow docs rebuild with custom getting started step. I.e. if `webtau` command line is available globally, then downloading zip is not required.
For that docs need to be rebuilt and hosted within a company with the additional .md file present.
=> getting started extension point for company specific overrides

pom.xml, webtau-dist/pom.xml, webtau-shaded/pom.xml
Not working yet. Current problem is I shade groovy as well and even though I use transformations, it doesn't shade properly `META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule`. I think it is because it is not in a standard `services` dir. 
Should we even shade Groovy? One of the reason I want to shade is to mitigate monorepo deps problems. Alternatively I could separate into groovy and non groovy jars.
=> Webtau uber jar + shading attempt

pom.xml, webtau-cli-testing/pom.xml, webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java, webtau-docs/webtau/REST/getting-started.md, webtau-docs/webtau/common/note-package-import.md, webtau-docs/webtau/lookup-paths, webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauCliArgsConfig.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/examples/DefaultExamplesProvider.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/examples/Example.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/examples/ExamplesProvider.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/examples/ExamplesScaffolder.groovy, webtau-groovy/src/main/resources/examples/todo/todolist.groovy, webtau-groovy/src/main/resources/examples/todo/webtau.cfg, webtau-junit4-examples/src/test/groovy/com/example/tests/featuretest/JUnitFeatureTestRunner.groovy, webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/TodoListGroovyIT.groovy, webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/WebTauFeaturesJUnitTest.groovy, webtau-junit4-examples/src/test/java/com/example/tests/junit4/TodoListJavaIT.java, webtau-junit4-examples/src/test/resources/webtau.properties, webtau-junit4-examples/test-expectations/TodoListGroovyIT/run-details.json, webtau-junit4-examples/test-expectations/TodoListJavaIT/run-details.json
Idea is users can just do `webtau --example` and run generated examples without any setup to get the feel for the tool.
Folks who wrap webtau can register their own examples that are, say, company specific.
There is a new module `webtau-cli-testing` that is a placeholder for now.
Need to figure out how to make webtau cli testing capabilities to test webtau cli itself (unzipped dist after assembly).
=> add --example option to bootstrap examples ready to be ran

.travis.yml, pom.xml, update-gh-pages.sh, webtau-docs/pom.xml, webtau-docs/webtau/UI/basic-configuration.md, webtau-feature-testing/examples/scenarios/ui/docCapture.cfg, webtau-feature-testing/src/main/groovy/com/twosigma/webtau/featuretesting/WebTauEndToEndTestRunner.groovy, webtau-json-schema/pom.xml, webtau-junit5-examples/pom.xml
Adding a number of things to make this happen:
1. turning on znai plugin to build and export docs
1. script for updating gh-pages
1. trigger this script from any tag build
1. unrelated to this overall change - minor cleanup to the webtau-junit5-examples pom following feedback in https://github.com/twosigma/webtau/pull/401
I tested the new script locally without doing a commit and push and got the following output from a git status in that dir:
```bash
~/OSSDev/webtau/gh-pages[gh-pages !x+]$ git status
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
modified:   guide/REST/CRUD-separated/index.html
modified:   guide/REST/CRUD/index.html
modified:   guide/REST/JSON-schema/index.html
modified: …
```
=> Update gh pages on release

.travis.yml, update-gh-pages.sh, webtau-docs/pom.xml
1. fix doc ID; the hosted pages have a `webtau/guide` prefix
1. fix update-gh-pages script for the new doc ID
1. remove invocation of update-gh-pages from Travis branch build as it currently does not work as Travis does not have permissions to push to the branch
=> Fix docs generation

.travis.yml
@tsiq-clemens has recently hit some differences between 8 and 11 in the context of the http url classes.  I'm making Travis build with both 8 and 11 in an attempt to catch such issues.
The two builds run in parallel so should not have any real impact on overall Travis build time.  Don't be confused by the time reported in Travis, that's a sum of all parallel jobs.
=> Build with multiple JDKs

webtau-http-groovy/src/test/groovy/com/twosigma/webtau/http/listeners/HttpListenersTest.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java, webtau-http/src/main/java/com/twosigma/webtau/http/listener/HttpListener.java, webtau-http/src/main/java/com/twosigma/webtau/http/listener/HttpListeners.java, webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationResult.java
```
public interface HttpListener {
default void beforeFirstHttpCall() {
}
default void beforeHttpCall(String requestMethod,
String passedUrl,
String fullUrl,
HttpHeader requestHeader,
HttpRequestBody requestBody) {
}
default void afterHttpCall(String requestMethod,
String passedUrl,
String fullUrl,
HttpHeader requestHeader,
HttpRequestBody requestBody,
HttpResponse response) {
}
}
```
`beforeFirstHttpCall` can be used to automatically bootstrap an embedded server
=> Introduce http listeners

pom.xml, webtau-browser/src/main/java/com/twosigma/webtau/browser/page/PageElement.java, webtau-browser/src/main/java/com/twosigma/webtau/browser/page/path/GenericPageElement.java, webtau-config/src/main/java/com/twosigma/webtau/cfg/WebTauConfig.java, webtau-core/src/main/java/com/twosigma/webtau/reporter/stacktrace/StackTraceUtils.java, webtau-groovy/pom.xml, webtau-groovy/repl-demo/webtau.cfg, webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauCliArgsConfig.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cfg/WebTauGroovyFileConfigHandler.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/WebTauCliApp.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/repl/Repl.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/repl/ReplCommands.groovy, webtau-groovy/src/main/groovy/com/twosigma/webtau/cli/repl/ReplHttpLastValidationCapture.groovy, webtau-http/src/main/java/com/twosigma/webtau/http/Http.java, webtau-http/src/main/java/com/twosigma/webtau/http/validation/HttpValidationHandlers.java
Wraps groovysh to expose webtau entities like `http.` and `browser.`. 
This is for interactive exploration of REST API or browser based testing.
Eventually it will merge `interactive` mode functionality in it and `interactive` mode will be removed.
=> initial repl for groovy

webtau-feature-testing/src/main/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauEndToEndTestRunner.groovy, webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauBrowserFeaturesTest.groovy, webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauRestFeaturesTest.groovy, webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauRestFeaturesTestData.groovy, webtau-http/src/test/java/org/testingisdocumenting/webtau/http/HttpTestDataServer.java, webtau-junit4-examples/src/test/groovy/com/example/tests/junit4/WebTauFeaturesJUnitTest.groovy, webtau-pdf/src/test/groovy/org/testingisdocumenting/webtau/pdf/PdfHttpTest.groovy, webtau-test-server/src/main/java/org/testingisdocumenting/webtau/http/testserver/FixedResponsesHandler.java, webtau-test-server/src/main/java/org/testingisdocumenting/webtau/http/testserver/TestServer.java
For GraphQL integration testing, I would like a more flexible approach than <method, url> to response mapping.  I've therefore split out the actual request handling from `TestServer` so it can be customised where it makes sense.
I wasn't completely happy to have various test classes know about Jetty's `Handler` but I also wasn't super thrilled to introduce an abstraction which in all likelihood would look almost identical.  Happy to hear your thoughts on the matter.
=> Split the response handling out of test server

pom.xml, webtau-feature-testing/examples/scenarios/graphql/queryAndMutation.groovy, webtau-feature-testing/pom.xml, webtau-feature-testing/test-expectations/scenarios/graphql/queryAndMutation/run-details.json, webtau-graphql-groovy/pom.xml, webtau-graphql-groovy/src/main/groovy/org/testingisdocumenting/webtau/graphql/GraphQLExtensions.groovy, webtau-graphql-groovy/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule, webtau-graphql-groovy/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLGroovyTest.groovy, webtau-graphql/pom.xml, webtau-graphql/src/main/java/org/testgisdocumenting/webtau/graphql/GraphQL.java, webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLJavaTest.java, webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestBase.java, webtau-graphql/src/test/java/org/testingisdocumenting/webtau/graphql/GraphQLTestDataServer.java, webtau-utils/src/main/java/org/testingisdocumenting/webtau/utils/CollectionUtils.java, webtau-utils/src/main/java/org/testingisdocumenting/webtau/utils/JsonUtils.java, webtau/pom.xml, webtau/src/main/java/org/testingisdocumenting/webtau/WebTauDsl.java
I know I haven't added any tests, I will do that before I merge this PR.  However, I wanted to open it now to start a discussion about the DSL so comments very welcome 😁 
Some questions, comments, food for thought, etc. below.  Once we have some sort of consensus I can break these up into issues.
I'm in two minds about how to handle the `errors`.  Initially I was going to have default assertions if the user does not provide any (like status code for example).
However, that may be annoying because there may be cases where you just don't care whether there are errors if all else is good so you'd want to disable the default handling.  I'm not sure that's a common case though so perhaps the default handling makes sense.
I think it would make sense to offer a better way to provide the query …
=> Initial graphql dsl support

webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauGraphQLFeaturesTest.groovy, webtau-groovy/src/main/groovy/org/testingisdocumenting/webtau/cli/WebTauCliApp.groovy, webtau-report/src/main/java/org/testingisdocumenting/webtau/report/ReportGenerators.java
Report Generators added using config file or explicit `.add` method are removed now at the end of tests run.
=> core: clear added generators at the end of tests run

webtau-feature-testing/examples/scenarios/graphql/Report.groovy, webtau-feature-testing/examples/scenarios/graphql/queryAndMutation.groovy, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoverage.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProvider.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchema.java, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProviderTest.groovy, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLSchemaTest.groovy, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/TestUtils.groovy
This changes two things:
1. fixes local build issues where `mvn package/install` would fail.  This was failing because `GraphQLReportDataProvider` grabbed a reference to `GraphQLCoverage` from `GraphQL` when the data provider was first constructed.  However, during tests, `GraphQL.reset()` ends up being invoked a number of times but nothing recreates the data provider.  Therefore we were recording the correct coverage, just not on the coverage object that the report data provider was using.
1. I had misunderstood slightly the internal representation of queries within the library we use for parsing.  I've addressed this and added some appropriate tests.  Unfortunately, we have overloaded the word "operation' and webtau's meaning of it (the name/type tuple, e.g. `query foo`) differs from …
=> Fix GraphQL query parsing

.gitignore, webtau-browser/src/test/groovy/org/testingisdocumenting/webtau/browser/documentation/BrowserDocumentationTest.groovy, webtau-config/src/main/java/org/testingisdocumenting/webtau/cfg/WebTauConfig.java
It's nice not to see a load of stuff in `git status` when you've not changed anything but have ran tests.  I've therefore added `doc-artifacts` to gitignore and also made one test generate its artifacts into that dir.
Ideally all these transient things that get generated by the build would go into `target` (and equivalent for npm) so that a clean removes them but that's a bit more work, this first step is easy and does a large part of the job.
=> build: leave clean working directory

webtau-maven-plugin/src/main/groovy/org/testingisdocumenting/webtau/maven/WebTauMaven.groovy
The order doesn't seem totally deterministic, at least not across OSes, so I suggest we sort alphabetically.
=> maven plugin: sort test files

webtau-docs/znai/GraphQL/getting-started.md, webtau-feature-testing/examples/scenarios/graphql/webtau-authed-graphql.cfg.groovy, webtau-feature-testing/examples/scenarios/graphql/webtau-report.cfg.groovy, webtau-feature-testing/examples/scenarios/graphql/webtau-weather.cfg.groovy, webtau-feature-testing/examples/scenarios/graphql/webtau.cfg.groovy, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQL.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLConfig.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchema.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLSchemaLoader.java, webtau-groovy/src/main/resources/examples/graphql/webtau.cfg.groovy, webtau-junit4-examples/src/test/resources/webtau-graphql.properties
I removed the `graphQLEnabled` flag but I have replaced it with `graphQLIgnoreIntrospectionFailures` so that people who want to be aware of such failures can be.
Fixes #702
=> remove graphQLEnabled flag

webtau-feature-testing/examples/scenarios/graphql/Report.groovy, webtau-feature-testing/examples/scenarios/graphql/TestReport.groovy, webtau-feature-testing/examples/scenarios/graphql/queryAndMutation.groovy, webtau-feature-testing/pom.xml, webtau-feature-testing/src/test/groovy/org/testingisdocumenting/webtau/featuretesting/WebTauGraphQLFeaturesTestData.groovy, webtau-feature-testing/test-expectations/scenarios/graphql/queryAndMutation/run-details.json, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoverage.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLCoveredQueries.java, webtau-graphql/src/main/java/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProvider.java, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLCoverageTest.groovy, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/GraphQLReportDataProviderTest.groovy, webtau-graphql/src/test/groovy/org/testingisdocumenting/webtau/graphql/TestUtils.groovy
Fixes #726 
Inspect the validation result to determine whether it was a success (no errors) or error outcome (errors != null), then use that information to gather and calculate success/error "branch" coverage for all defined graphql operations.
=> webtau-726 compute success and error branch coverage

webtau-cli-groovy/scripts/loop, webtau-cli-groovy/src/test/groovy/org/testingisdocumenting/webtau/cli/CliConcurrencyTest.groovy, webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/CliOutput.java, webtau-cli/src/main/java/org/testingisdocumenting/webtau/cli/StreamGobbler.java
@tsiq-karold could you please take a look? I am not sure if there is a better java way to make it concurrency-proof.
=> cli: fix concurrent modification on output wait

webtau-core/src/main/java/org/testingisdocumenting/webtau/reporter/WebTauTest.java, webtau-feature-testing/examples/listeners/MetadataValidationTestListener.groovy, webtau-standalone-runner-groovy/src/main/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTest.groovy, webtau-standalone-runner-groovy/src/main/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTestRunner.groovy, webtau-standalone-runner-groovy/src/test/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTestRunnerTest.groovy, webtau-standalone-runner-groovy/src/test/groovy/org/testingisdocumenting/webtau/runner/standalone/StandaloneTestTest.groovy
Fixes https://github.com/testingisdocumenting/webtau/issues/765
Mark auto-generated `WebTauTest` as synthetic; that makes it more elegant to exclude them from metadata checks.
=> add support for synthetic tests

webtau-config/src/main/java/org/testingisdocumenting/webtau/cfg/WebTauConfig.java
`httpTimeout` is not overridable yet, so it always uses the default value
=> core: add httpTimeout to overridable config values

webtau-core/src/main/java/org/testingisdocumenting/webtau/expectation/equality/handlers/HandlerMessages.java
... so that developers can reuse the reporting logic in their custom handlers
=> core: make HandlerMessages public 
